name: pyautogui_demo
dependencies:
- python=3.7.9
- pip
- pip:
  - keyboard
  - pywin32
  - pyautogui
  - opencv-python
  
# Things that fail dependencies:
#- pip:

# opencv needed for the locateOnScreen...
